"""
Bug Report template generator (Word documents)
"""
from typing import List, Optional
from pathlib import Path
from datetime import datetime
from docx import Document
from docx.shared import Inches, Pt, RGBColor
from docx.enum.text import WD_ALIGN_PARAGRAPH

from backend.models import BugReport, BugSeverity, BugPriority, BugType, BugStatus


class BugReportGenerator:
    """Generator for bug report templates and documents"""

    def __init__(self):
        pass

    def generate_template(self, output_dir: str, filename: str = "BugReportTemplate.docx") -> str:
        """
        Generate a blank bug report template

        Args:
            output_dir: Output directory
            filename: Template filename

        Returns:
            Path to generated template
        """
        output_path = Path(output_dir)
        output_path.mkdir(parents=True, exist_ok=True)

        doc = Document()

        # Title
        title = doc.add_heading("Bug Report Template", 0)
        title.alignment = WD_ALIGN_PARAGRAPH.CENTER

        # Bug ID and basic info
        doc.add_heading("1. Bug Information", level=1)
        table = doc.add_table(rows=8, cols=2)
        table.style = "Light Grid Accent 1"

        # Fill in template fields
        fields = [
            ("Bug ID:", "[BUG-XXX]"),
            ("Title:", "[Brief description]"),
            ("Reported By:", "[Your Name]"),
            ("Date Reported:", f"{datetime.now().strftime('%Y-%m-%d')}"),
            ("Severity:", "[Critical/High/Medium/Low]"),
            ("Priority:", "[Urgent/High/Medium/Low]"),
            ("Status:", "[New/Assigned/In Progress/Fixed/Closed]"),
            ("Type:", "[Functional/UI/Performance/Security/etc.]"),
        ]

        for i, (label, value) in enumerate(fields):
            table.rows[i].cells[0].text = label
            table.rows[i].cells[1].text = value

        # Description
        doc.add_heading("2. Description", level=1)
        doc.add_paragraph(
            "Provide a detailed description of the bug. What is the issue?"
        )

        # Steps to reproduce
        doc.add_heading("3. Steps to Reproduce", level=1)
        doc.add_paragraph("1. [Step 1]")
        doc.add_paragraph("2. [Step 2]")
        doc.add_paragraph("3. [Step 3]")

        # Expected vs Actual
        doc.add_heading("4. Expected Behavior", level=1)
        doc.add_paragraph("[Describe what should happen]")

        doc.add_heading("5. Actual Behavior", level=1)
        doc.add_paragraph("[Describe what actually happens]")

        # Environment
        doc.add_heading("6. Environment", level=1)
        env_table = doc.add_table(rows=4, cols=2)
        env_table.style = "Light Grid Accent 1"

        env_fields = [
            ("Environment:", "[Dev/QA/Staging/Production]"),
            ("Browser/Client:", "[Chrome 120, Firefox 119, etc.]"),
            ("Operating System:", "[Windows 11, macOS 14, etc.]"),
            ("Application Version:", "[v1.0.0]"),
        ]

        for i, (label, value) in enumerate(env_fields):
            env_table.rows[i].cells[0].text = label
            env_table.rows[i].cells[1].text = value

        # Screenshots
        doc.add_heading("7. Screenshots/Attachments", level=1)
        doc.add_paragraph("[Attach screenshots, logs, or videos here]")

        # Additional notes
        doc.add_heading("8. Additional Notes", level=1)
        doc.add_paragraph("[Any additional information that might be helpful]")

        # Footer
        doc.add_paragraph()
        footer = doc.add_paragraph("Generated by QA Documentation Automation System")
        footer.alignment = WD_ALIGN_PARAGRAPH.CENTER
        footer.runs[0].font.size = Pt(9)
        footer.runs[0].font.color.rgb = RGBColor(128, 128, 128)

        # Save document
        file_path = output_path / filename
        doc.save(str(file_path))

        return str(file_path)

    def generate_bug_report(
        self, bug: BugReport, output_dir: str, filename: Optional[str] = None
    ) -> str:
        """
        Generate a filled bug report document

        Args:
            bug: BugReport object
            output_dir: Output directory
            filename: Optional custom filename

        Returns:
            Path to generated document
        """
        output_path = Path(output_dir)
        output_path.mkdir(parents=True, exist_ok=True)

        if not filename:
            filename = f"BugReport_{bug.id}_{datetime.now().strftime('%Y%m%d')}.docx"

        doc = Document()

        # Title
        title = doc.add_heading(f"Bug Report: {bug.title}", 0)
        title.alignment = WD_ALIGN_PARAGRAPH.CENTER

        # Bug ID and basic info
        doc.add_heading("1. Bug Information", level=1)
        table = doc.add_table(rows=8, cols=2)
        table.style = "Light Grid Accent 1"

        # Fill in bug data
        fields = [
            ("Bug ID:", bug.id or "TBD"),
            ("Title:", bug.title),
            ("Reported By:", bug.reported_by or "N/A"),
            (
                "Date Reported:",
                bug.reported_date.strftime("%Y-%m-%d")
                if bug.reported_date
                else datetime.now().strftime("%Y-%m-%d"),
            ),
            ("Severity:", bug.severity.value),
            ("Priority:", bug.priority.value),
            ("Status:", bug.status.value),
            ("Type:", bug.bug_type.value),
        ]

        for i, (label, value) in enumerate(fields):
            table.rows[i].cells[0].text = label
            table.rows[i].cells[1].text = str(value)
            # Bold the labels
            table.rows[i].cells[0].paragraphs[0].runs[0].font.bold = True

        # Color code severity
        severity_cell = table.rows[4].cells[1]
        severity_color = self._get_severity_color(bug.severity)
        severity_cell.paragraphs[0].runs[0].font.color.rgb = severity_color

        # Description
        doc.add_heading("2. Description", level=1)
        doc.add_paragraph(bug.description)

        # Steps to reproduce
        doc.add_heading("3. Steps to Reproduce", level=1)
        for i, step in enumerate(bug.steps_to_reproduce, 1):
            doc.add_paragraph(f"{i}. {step}")

        # Expected vs Actual
        doc.add_heading("4. Expected Behavior", level=1)
        doc.add_paragraph(bug.expected_behavior)

        doc.add_heading("5. Actual Behavior", level=1)
        doc.add_paragraph(bug.actual_behavior)

        # Environment
        doc.add_heading("6. Environment", level=1)
        env_table = doc.add_table(rows=4, cols=2)
        env_table.style = "Light Grid Accent 1"

        env_fields = [
            ("Environment:", bug.environment or "N/A"),
            ("Browser/Client:", bug.browser or "N/A"),
            ("Operating System:", bug.os or "N/A"),
            ("Application Version:", bug.version or "N/A"),
        ]

        for i, (label, value) in enumerate(env_fields):
            env_table.rows[i].cells[0].text = label
            env_table.rows[i].cells[1].text = str(value)
            env_table.rows[i].cells[0].paragraphs[0].runs[0].font.bold = True

        # Related information
        if bug.user_story_id or bug.test_case_id or bug.scenario_name:
            doc.add_heading("7. Related Items", level=1)
            if bug.user_story_id:
                doc.add_paragraph(f"User Story: {bug.user_story_id}")
            if bug.test_case_id:
                doc.add_paragraph(f"Test Case: {bug.test_case_id}")
            if bug.scenario_name:
                doc.add_paragraph(f"Scenario: {bug.scenario_name}")
            if bug.related_bugs:
                doc.add_paragraph(f"Related Bugs: {', '.join(bug.related_bugs)}")

        # Screenshots/attachments
        doc.add_heading("8. Screenshots/Attachments", level=1)
        if bug.screenshots:
            for screenshot in bug.screenshots:
                doc.add_paragraph(f"• {screenshot}")
        else:
            doc.add_paragraph("[No attachments]")

        # Logs
        if bug.logs:
            doc.add_heading("9. Relevant Logs", level=1)
            log_para = doc.add_paragraph(bug.logs)
            log_para.style = "Intense Quote"

        # Workaround
        if bug.workaround:
            doc.add_heading("10. Workaround", level=1)
            doc.add_paragraph(bug.workaround)

        # Additional notes
        if bug.notes:
            doc.add_heading("11. Additional Notes", level=1)
            doc.add_paragraph(bug.notes)

        # Footer
        doc.add_paragraph()
        footer = doc.add_paragraph(
            f"Generated by QA Documentation Automation System on {datetime.now().strftime('%Y-%m-%d %H:%M')}"
        )
        footer.alignment = WD_ALIGN_PARAGRAPH.CENTER
        footer.runs[0].font.size = Pt(9)
        footer.runs[0].font.color.rgb = RGBColor(128, 128, 128)

        # Save document
        file_path = output_path / filename
        doc.save(str(file_path))

        return str(file_path)

    def generate_bulk_report(
        self, bugs: List[BugReport], output_dir: str, filename: str = "BugSummaryReport.docx"
    ) -> str:
        """
        Generate a summary report of multiple bugs grouped by Test Case and Scenario

        Args:
            bugs: List of BugReport objects
            output_dir: Output directory
            filename: Report filename

        Returns:
            Path to generated report
        """
        output_path = Path(output_dir)
        output_path.mkdir(parents=True, exist_ok=True)

        doc = Document()

        # Title
        title = doc.add_heading("Bug Summary Report", 0)
        title.alignment = WD_ALIGN_PARAGRAPH.CENTER

        # Date
        date_para = doc.add_paragraph(f"Generated: {datetime.now().strftime('%Y-%m-%d %H:%M')}")
        date_para.alignment = WD_ALIGN_PARAGRAPH.CENTER

        # Summary statistics
        doc.add_heading("Executive Summary", level=1)
        doc.add_paragraph(f"Total Bugs Reported: {len(bugs)}")

        # Count by severity
        severity_counts = self._count_by_attribute(bugs, "severity")
        doc.add_paragraph("By Severity:")
        for severity, count in severity_counts.items():
            doc.add_paragraph(f"  • {severity}: {count}", style="List Bullet 2")

        # Count by priority
        priority_counts = self._count_by_attribute(bugs, "priority")
        doc.add_paragraph("By Priority:")
        for priority, count in priority_counts.items():
            doc.add_paragraph(f"  • {priority}: {count}", style="List Bullet 2")

        # Count by status
        status_counts = self._count_by_attribute(bugs, "status")
        doc.add_paragraph("By Status:")
        for status, count in status_counts.items():
            doc.add_paragraph(f"  • {status}: {count}", style="List Bullet 2")

        # Group bugs by test_case_id and scenario_name
        grouped_bugs = self._group_bugs_by_test_case_and_scenario(bugs)

        # Detailed bug list (grouped)
        doc.add_heading("Bugs by Test Case and Scenario", level=1)

        if not grouped_bugs:
            doc.add_paragraph("No bugs to display.")
        else:
            for test_case_id, scenarios in sorted(grouped_bugs.items()):
                # Test Case heading
                doc.add_heading(f"Test Case: {test_case_id}", level=2)

                for scenario_name, scenario_bugs in sorted(scenarios.items()):
                    # Scenario subheading
                    scenario_heading = doc.add_heading(f"Scenario: {scenario_name}", level=3)
                    scenario_heading.paragraph_format.left_indent = Inches(0.25)

                    # Bugs count
                    doc.add_paragraph(f"({len(scenario_bugs)} bug{'s' if len(scenario_bugs) > 1 else ''})")

                    # Show detailed information for each bug
                    for bug in scenario_bugs:
                        # Bug header with ID and Title
                        bug_heading = doc.add_heading(f"Bug: {bug.id or 'TBD'} - {bug.title}", level=4)
                        bug_heading.paragraph_format.left_indent = Inches(0.5)

                        # Status badges
                        status_para = doc.add_paragraph()
                        status_para.paragraph_format.left_indent = Inches(0.5)

                        # Add severity with color
                        severity_run = status_para.add_run(f"⚠️ {bug.severity.value}")
                        severity_run.font.color.rgb = self._get_severity_color(bug.severity)
                        severity_run.font.bold = True
                        status_para.add_run(f"  |  Priority: {bug.priority.value}")
                        status_para.add_run(f"  |  Status: {bug.status.value}")
                        status_para.add_run(f"  |  Type: {bug.bug_type.value}")

                        # Steps to Reproduce
                        if bug.steps_to_reproduce:
                            steps_para = doc.add_paragraph()
                            steps_para.paragraph_format.left_indent = Inches(0.5)
                            steps_run = steps_para.add_run("📋 Steps to Reproduce:")
                            steps_run.bold = True
                            for i, step in enumerate(bug.steps_to_reproduce, 1):
                                step_para = doc.add_paragraph(f"{i}. {step}", style="List Number 2")
                                step_para.paragraph_format.left_indent = Inches(0.75)

                        # Expected vs Actual (side by side table)
                        if bug.expected_behavior or bug.actual_behavior:
                            comparison_para = doc.add_paragraph()
                            comparison_para.paragraph_format.left_indent = Inches(0.5)
                            comparison_run = comparison_para.add_run("✅ Expected vs ❌ Actual:")
                            comparison_run.bold = True

                            comparison_table = doc.add_table(rows=2, cols=2)
                            comparison_table.style = "Light Grid Accent 1"

                            # Headers
                            comparison_table.rows[0].cells[0].text = "Expected Behavior"
                            comparison_table.rows[0].cells[1].text = "Actual Behavior"
                            for cell in comparison_table.rows[0].cells:
                                cell.paragraphs[0].runs[0].font.bold = True

                            # Content
                            comparison_table.rows[1].cells[0].text = bug.expected_behavior or "N/A"
                            comparison_table.rows[1].cells[1].text = bug.actual_behavior or "N/A"

                        # Environment Details
                        if bug.environment or bug.browser or bug.os or bug.version:
                            env_para = doc.add_paragraph()
                            env_para.paragraph_format.left_indent = Inches(0.5)
                            env_run = env_para.add_run("🌐 Environment:")
                            env_run.bold = True

                            env_details = []
                            if bug.environment:
                                env_details.append(f"Env: {bug.environment}")
                            if bug.browser:
                                env_details.append(f"Browser: {bug.browser}")
                            if bug.os:
                                env_details.append(f"OS: {bug.os}")
                            if bug.version:
                                env_details.append(f"Version: {bug.version}")

                            env_text = "  •  ".join(env_details)
                            detail_para = doc.add_paragraph(env_text)
                            detail_para.paragraph_format.left_indent = Inches(0.75)

                        # Screenshots/Attachments
                        if bug.screenshots:
                            screenshot_para = doc.add_paragraph()
                            screenshot_para.paragraph_format.left_indent = Inches(0.5)
                            screenshot_run = screenshot_para.add_run("🖼️ Screenshots:")
                            screenshot_run.bold = True
                            for screenshot in bug.screenshots:
                                img_para = doc.add_paragraph(f"• {screenshot}", style="List Bullet 2")
                                img_para.paragraph_format.left_indent = Inches(0.75)

                        # Reported by
                        reported_para = doc.add_paragraph()
                        reported_para.paragraph_format.left_indent = Inches(0.5)
                        reported_para.add_run(f"👤 Reported by: {bug.reported_by or 'N/A'}")
                        if bug.reported_date:
                            reported_para.add_run(f"  |  📅 Date: {bug.reported_date.strftime('%Y-%m-%d')}")

                        # Add spacing between bugs
                        doc.add_paragraph()

                    doc.add_paragraph()  # Add spacing between scenarios

        # Footer
        doc.add_paragraph()
        footer = doc.add_paragraph(
            f"Generated by QA Documentation Automation System • {datetime.now().strftime('%Y-%m-%d %H:%M')}"
        )
        footer.alignment = WD_ALIGN_PARAGRAPH.CENTER
        footer.runs[0].font.size = Pt(9)
        footer.runs[0].font.color.rgb = RGBColor(128, 128, 128)

        # Save document
        file_path = output_path / filename
        doc.save(str(file_path))

        return str(file_path)

    def _group_bugs_by_test_case_and_scenario(self, bugs: List[BugReport]) -> dict:
        """
        Group bugs by test_case_id and scenario_name

        Returns:
            Dict structure: {test_case_id: {scenario_name: [bugs]}}
        """
        from collections import defaultdict

        grouped = defaultdict(lambda: defaultdict(list))

        for bug in bugs:
            test_case_id = bug.test_case_id if bug.test_case_id else "No Test Case"
            scenario_name = bug.scenario_name if bug.scenario_name else "No Scenario"
            grouped[test_case_id][scenario_name].append(bug)

        return dict(grouped)

    def _get_severity_color(self, severity: BugSeverity) -> RGBColor:
        """Get color for severity level"""
        colors = {
            BugSeverity.CRITICAL: RGBColor(255, 0, 0),  # Red
            BugSeverity.HIGH: RGBColor(255, 165, 0),  # Orange
            BugSeverity.MEDIUM: RGBColor(255, 215, 0),  # Gold
            BugSeverity.LOW: RGBColor(0, 128, 0),  # Green
        }
        return colors.get(severity, RGBColor(0, 0, 0))

    def _count_by_attribute(self, bugs: List[BugReport], attribute: str) -> dict:
        """Count bugs by a specific attribute"""
        counts = {}
        for bug in bugs:
            value = getattr(bug, attribute)
            if hasattr(value, "value"):
                value = value.value
            counts[str(value)] = counts.get(str(value), 0) + 1
        return dict(sorted(counts.items()))
