"""
Bug Report template generator (Word documents)
"""
from typing import List, Optional
from pathlib import Path
from datetime import datetime
from docx import Document
from docx.shared import Inches, Pt, RGBColor
from docx.enum.text import WD_ALIGN_PARAGRAPH

from backend.models import BugReport, BugSeverity, BugPriority, BugType, BugStatus


class BugReportGenerator:
    """Generator for bug report templates and documents"""

    def __init__(self):
        pass

    def generate_template(self, output_dir: str, filename: str = "BugReportTemplate.docx") -> str:
        """
        Generate a blank bug report template

        Args:
            output_dir: Output directory
            filename: Template filename

        Returns:
            Path to generated template
        """
        output_path = Path(output_dir)
        output_path.mkdir(parents=True, exist_ok=True)

        doc = Document()

        # Title
        title = doc.add_heading("Bug Report Template", 0)
        title.alignment = WD_ALIGN_PARAGRAPH.CENTER

        # Bug ID and basic info
        doc.add_heading("1. Bug Information", level=1)
        table = doc.add_table(rows=8, cols=2)
        table.style = "Light Grid Accent 1"

        # Fill in template fields
        fields = [
            ("Bug ID:", "[BUG-XXX]"),
            ("Title:", "[Brief description]"),
            ("Reported By:", "[Your Name]"),
            ("Date Reported:", f"{datetime.now().strftime('%Y-%m-%d')}"),
            ("Severity:", "[Critical/High/Medium/Low]"),
            ("Priority:", "[Urgent/High/Medium/Low]"),
            ("Status:", "[New/Assigned/In Progress/Fixed/Closed]"),
            ("Type:", "[Functional/UI/Performance/Security/etc.]"),
        ]

        for i, (label, value) in enumerate(fields):
            table.rows[i].cells[0].text = label
            table.rows[i].cells[1].text = value

        # Description
        doc.add_heading("2. Description", level=1)
        doc.add_paragraph(
            "Provide a detailed description of the bug. What is the issue?"
        )

        # Steps to reproduce
        doc.add_heading("3. Steps to Reproduce", level=1)
        doc.add_paragraph("1. [Step 1]")
        doc.add_paragraph("2. [Step 2]")
        doc.add_paragraph("3. [Step 3]")

        # Expected vs Actual
        doc.add_heading("4. Expected Behavior", level=1)
        doc.add_paragraph("[Describe what should happen]")

        doc.add_heading("5. Actual Behavior", level=1)
        doc.add_paragraph("[Describe what actually happens]")

        # Environment
        doc.add_heading("6. Environment", level=1)
        env_table = doc.add_table(rows=4, cols=2)
        env_table.style = "Light Grid Accent 1"

        env_fields = [
            ("Environment:", "[Dev/QA/Staging/Production]"),
            ("Browser/Client:", "[Chrome 120, Firefox 119, etc.]"),
            ("Operating System:", "[Windows 11, macOS 14, etc.]"),
            ("Application Version:", "[v1.0.0]"),
        ]

        for i, (label, value) in enumerate(env_fields):
            env_table.rows[i].cells[0].text = label
            env_table.rows[i].cells[1].text = value

        # Screenshots
        doc.add_heading("7. Screenshots/Attachments", level=1)
        doc.add_paragraph("[Attach screenshots, logs, or videos here]")

        # Additional notes
        doc.add_heading("8. Additional Notes", level=1)
        doc.add_paragraph("[Any additional information that might be helpful]")

        # Footer
        doc.add_paragraph()
        footer = doc.add_paragraph("Generated by QA Documentation Automation System")
        footer.alignment = WD_ALIGN_PARAGRAPH.CENTER
        footer.runs[0].font.size = Pt(9)
        footer.runs[0].font.color.rgb = RGBColor(128, 128, 128)

        # Save document
        file_path = output_path / filename
        doc.save(str(file_path))

        return str(file_path)

    def generate_bug_report(
        self, bug: BugReport, output_dir: str, filename: Optional[str] = None
    ) -> str:
        """
        Generate a filled bug report document

        Args:
            bug: BugReport object
            output_dir: Output directory
            filename: Optional custom filename

        Returns:
            Path to generated document
        """
        output_path = Path(output_dir)
        output_path.mkdir(parents=True, exist_ok=True)

        if not filename:
            filename = f"BugReport_{bug.id}_{datetime.now().strftime('%Y%m%d')}.docx"

        doc = Document()

        # Title
        title = doc.add_heading(f"Bug Report: {bug.title}", 0)
        title.alignment = WD_ALIGN_PARAGRAPH.CENTER

        # Bug ID and basic info
        doc.add_heading("1. Bug Information", level=1)
        table = doc.add_table(rows=8, cols=2)
        table.style = "Light Grid Accent 1"

        # Fill in bug data
        fields = [
            ("Bug ID:", bug.id or "TBD"),
            ("Title:", bug.title),
            ("Reported By:", bug.reported_by or "N/A"),
            (
                "Date Reported:",
                bug.reported_date.strftime("%Y-%m-%d")
                if bug.reported_date
                else datetime.now().strftime("%Y-%m-%d"),
            ),
            ("Severity:", bug.severity.value),
            ("Priority:", bug.priority.value),
            ("Status:", bug.status.value),
            ("Type:", bug.bug_type.value),
        ]

        for i, (label, value) in enumerate(fields):
            table.rows[i].cells[0].text = label
            table.rows[i].cells[1].text = str(value)
            # Bold the labels
            table.rows[i].cells[0].paragraphs[0].runs[0].font.bold = True

        # Color code severity
        severity_cell = table.rows[4].cells[1]
        severity_color = self._get_severity_color(bug.severity)
        severity_cell.paragraphs[0].runs[0].font.color.rgb = severity_color

        # Description
        doc.add_heading("2. Description", level=1)
        doc.add_paragraph(bug.description)

        # Steps to reproduce
        doc.add_heading("3. Steps to Reproduce", level=1)
        for i, step in enumerate(bug.steps_to_reproduce, 1):
            doc.add_paragraph(f"{i}. {step}")

        # Expected vs Actual
        doc.add_heading("4. Expected Behavior", level=1)
        doc.add_paragraph(bug.expected_behavior)

        doc.add_heading("5. Actual Behavior", level=1)
        doc.add_paragraph(bug.actual_behavior)

        # Environment
        doc.add_heading("6. Environment", level=1)
        env_table = doc.add_table(rows=4, cols=2)
        env_table.style = "Light Grid Accent 1"

        env_fields = [
            ("Environment:", bug.environment or "N/A"),
            ("Browser/Client:", bug.browser or "N/A"),
            ("Operating System:", bug.os or "N/A"),
            ("Application Version:", bug.version or "N/A"),
        ]

        for i, (label, value) in enumerate(env_fields):
            env_table.rows[i].cells[0].text = label
            env_table.rows[i].cells[1].text = str(value)
            env_table.rows[i].cells[0].paragraphs[0].runs[0].font.bold = True

        # Related information
        if bug.user_story_id or bug.test_case_id:
            doc.add_heading("7. Related Items", level=1)
            if bug.user_story_id:
                doc.add_paragraph(f"User Story: {bug.user_story_id}")
            if bug.test_case_id:
                doc.add_paragraph(f"Test Case: {bug.test_case_id}")
            if bug.related_bugs:
                doc.add_paragraph(f"Related Bugs: {', '.join(bug.related_bugs)}")

        # Screenshots/attachments
        doc.add_heading("8. Screenshots/Attachments", level=1)
        if bug.screenshots:
            for screenshot in bug.screenshots:
                doc.add_paragraph(f"• {screenshot}")
        else:
            doc.add_paragraph("[No attachments]")

        # Logs
        if bug.logs:
            doc.add_heading("9. Relevant Logs", level=1)
            log_para = doc.add_paragraph(bug.logs)
            log_para.style = "Intense Quote"

        # Workaround
        if bug.workaround:
            doc.add_heading("10. Workaround", level=1)
            doc.add_paragraph(bug.workaround)

        # Additional notes
        if bug.notes:
            doc.add_heading("11. Additional Notes", level=1)
            doc.add_paragraph(bug.notes)

        # Footer
        doc.add_paragraph()
        footer = doc.add_paragraph(
            f"Generated by QA Documentation Automation System on {datetime.now().strftime('%Y-%m-%d %H:%M')}"
        )
        footer.alignment = WD_ALIGN_PARAGRAPH.CENTER
        footer.runs[0].font.size = Pt(9)
        footer.runs[0].font.color.rgb = RGBColor(128, 128, 128)

        # Save document
        file_path = output_path / filename
        doc.save(str(file_path))

        return str(file_path)

    def generate_bulk_report(
        self, bugs: List[BugReport], output_dir: str, filename: str = "BugSummaryReport.docx"
    ) -> str:
        """
        Generate a summary report of multiple bugs

        Args:
            bugs: List of BugReport objects
            output_dir: Output directory
            filename: Report filename

        Returns:
            Path to generated report
        """
        output_path = Path(output_dir)
        output_path.mkdir(parents=True, exist_ok=True)

        doc = Document()

        # Title
        title = doc.add_heading("Bug Summary Report", 0)
        title.alignment = WD_ALIGN_PARAGRAPH.CENTER

        # Date
        date_para = doc.add_paragraph(f"Generated: {datetime.now().strftime('%Y-%m-%d %H:%M')}")
        date_para.alignment = WD_ALIGN_PARAGRAPH.CENTER

        # Summary statistics
        doc.add_heading("Summary", level=1)
        doc.add_paragraph(f"Total Bugs: {len(bugs)}")

        # Count by severity
        severity_counts = self._count_by_attribute(bugs, "severity")
        doc.add_paragraph("By Severity:")
        for severity, count in severity_counts.items():
            doc.add_paragraph(f"  • {severity}: {count}", style="List Bullet 2")

        # Count by priority
        priority_counts = self._count_by_attribute(bugs, "priority")
        doc.add_paragraph("By Priority:")
        for priority, count in priority_counts.items():
            doc.add_paragraph(f"  • {priority}: {count}", style="List Bullet 2")

        # Count by status
        status_counts = self._count_by_attribute(bugs, "status")
        doc.add_paragraph("By Status:")
        for status, count in status_counts.items():
            doc.add_paragraph(f"  • {status}: {count}", style="List Bullet 2")

        # Detailed bug list
        doc.add_heading("Detailed Bug List", level=1)

        # Create table
        table = doc.add_table(rows=1, cols=6)
        table.style = "Light Grid Accent 1"

        # Header row
        headers = ["ID", "Title", "Severity", "Priority", "Status", "Type"]
        header_cells = table.rows[0].cells
        for i, header in enumerate(headers):
            header_cells[i].text = header
            header_cells[i].paragraphs[0].runs[0].font.bold = True

        # Add bugs
        for bug in bugs:
            row_cells = table.add_row().cells
            row_cells[0].text = bug.id or "TBD"
            row_cells[1].text = bug.title[:50] + "..." if len(bug.title) > 50 else bug.title
            row_cells[2].text = bug.severity.value
            row_cells[3].text = bug.priority.value
            row_cells[4].text = bug.status.value
            row_cells[5].text = bug.bug_type.value

        # Footer
        doc.add_paragraph()
        footer = doc.add_paragraph("Generated by QA Documentation Automation System")
        footer.alignment = WD_ALIGN_PARAGRAPH.CENTER
        footer.runs[0].font.size = Pt(9)
        footer.runs[0].font.color.rgb = RGBColor(128, 128, 128)

        # Save document
        file_path = output_path / filename
        doc.save(str(file_path))

        return str(file_path)

    def _get_severity_color(self, severity: BugSeverity) -> RGBColor:
        """Get color for severity level"""
        colors = {
            BugSeverity.CRITICAL: RGBColor(255, 0, 0),  # Red
            BugSeverity.HIGH: RGBColor(255, 165, 0),  # Orange
            BugSeverity.MEDIUM: RGBColor(255, 215, 0),  # Gold
            BugSeverity.LOW: RGBColor(0, 128, 0),  # Green
        }
        return colors.get(severity, RGBColor(0, 0, 0))

    def _count_by_attribute(self, bugs: List[BugReport], attribute: str) -> dict:
        """Count bugs by a specific attribute"""
        counts = {}
        for bug in bugs:
            value = getattr(bug, attribute)
            if hasattr(value, "value"):
                value = value.value
            counts[str(value)] = counts.get(str(value), 0) + 1
        return dict(sorted(counts.items()))
